@baseURL = http://localhost:4000/professor

//POST um novo professor
###
POST {{baseURL}}
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjY1YjNlODMzNGNmMjc0NWE4MDk2MWI4In0sImlhdCI6MTcxNzQyMjY1NCwiZXhwIjoxNzE3NTA5MDU0fQ.oENOJjJ_C0CDSNaQn5I4-B5lU80FLCVOj0gP58BjpX0

{
    "nome": "Jorge"   
}

//GET todos os professores
###
GET {{baseURL}}
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjY1YjNlODMzNGNmMjc0NWE4MDk2MWI4In0sImlhdCI6MTcxNzQyMjY1NCwiZXhwIjoxNzE3NTA5MDU0fQ.oENOJjJ_C0CDSNaQn5I4-B5lU80FLCVOj0gP58BjpX0

{

}

//GET o professor pelo id
###
GET {{baseURL}}/665b3ef034cf2745a80961bd
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjY1YjNlODMzNGNmMjc0NWE4MDk2MWI4In0sImlhdCI6MTcxNzQyMjY1NCwiZXhwIjoxNzE3NTA5MDU0fQ.oENOJjJ_C0CDSNaQn5I4-B5lU80FLCVOj0gP58BjpX0

{
    
}

//DELETE o professor pelo id
###
DELETE {{baseURL}}/665b3ef034cf2745a80961bd
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjY1YjNlODMzNGNmMjc0NWE4MDk2MWI4In0sImlhdCI6MTcxNzQyMjY1NCwiZXhwIjoxNzE3NTA5MDU0fQ.oENOJjJ_C0CDSNaQn5I4-B5lU80FLCVOj0gP58BjpX0

{
    
}