@baseURL = http://localhost:4000/professor

###
POST {{baseURL}}/create
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjY1YjNlODMzNGNmMjc0NWE4MDk2MWI4In0sImlhdCI6MTcxNzI1NTgyNywiZXhwIjoxNzE3MzQyMjI3fQ.RS8rpGKat7L3D91UpGTVVm4L6s3lYAGRMfPPWmvxLzE

{
    "nome": "Rodrigo"   
}